version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: fpm/Dockerfile
    container_name: php_app
    env_file:
      - /var/www/html/.env
    volumes:
        - ./app:/var/www/html
        - /var/www/html/vendor
    networks:
        - app-network
    depends_on:
        - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./app:/var/www/html
    ports:
        - "80:80"
        - "443:443"
    networks:
        - app-network
    depends_on:
        - app

  postgres:
    image: postgres
    container_name: postgres-truck-api
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./local_pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
